import { type TenantContext } from "@jk/domain-kernel";
import type pg from "pg";

/**
 * Authorization for Analytics and Intelligence (§66). Generating and
 * acting on alerts is an operational write; reports and alert listing are
 * reads. Alerts may also be generated by a scheduled service/worker actor.
 */
export type AnalyticsAction = "manage_alerts" | "read";

const WRITE_ROLES = new Set([
  "tenant_owner",
  "farm_manager",
  "technician",
  "veterinarian",
]);

export interface CallerMembership {
  role: string;
  status: string;
}

export interface AnalyticsDecision {
  allowed: boolean;
  reason: string;
  action: AnalyticsAction;
}

export async function loadCallerMemberships(
  client: pg.PoolClient,
  context: TenantContext,
): Promise<CallerMembership[]> {
  if (context.actor.type !== "user") return [];
  const result = await client.query<CallerMembership>(
    `SELECT role, status FROM tenant_membership
     WHERE tenant_id = $1 AND user_id = $2 AND valid_to IS NULL`,
    [context.tenantId, context.actor.id],
  );
  return result.rows;
}

export function decide(
  action: AnalyticsAction,
  context: TenantContext,
  memberships: readonly CallerMembership[],
): AnalyticsDecision {
  // A scheduled service/worker actor may generate alerts.
  if (action === "manage_alerts" && context.actor.type === "service") {
    return { allowed: true, reason: "scheduled_actor", action };
  }
  const active = memberships.filter((m) => m.status === "active");
  if (active.length === 0)
    return { allowed: false, reason: "no_active_membership", action };
  if (action === "read") return { allowed: true, reason: "active_member", action };
  const ok = active.some((m) => WRITE_ROLES.has(m.role));
  return ok
    ? { allowed: true, reason: "authorized_role", action }
    : { allowed: false, reason: `role not permitted for ${action}`, action };
}
